export const INC_COUNTER = 'INC_COUNTER';
export const DEC_COUNTER = 'DEC_COUNTER';

export const PING_MARQETA = 'PING_MARQETA';
export const MARQETA_GET_USER = 'MARQETA_GET_USER';
export const MARQETA_GET_BALANCES = 'MARQETA_GET_BALANCES';
export const MARQETA_LOGIN = 'MARQETA_LOGIN';
